### ISSUE TITLE
which one reflects to GPU memory, and which one reflects CPU memory

### ISSUE THREAD

**Issue by hellobb237** [albanie/convnet-burden#9]
I see two memories listed here: parameter memory and feature memory. When we plan hardware for inference work, should we put them together as a requirement to memory size of GPU card? thanks

**Comment by albanie** [comment]
Hi @hellobb237, typically for inference, the parameters will be loaded into memory, but the features in each layer are dropped after they are computed and no longer needed in the forward pass, so the effective memory requirement is significantly lower than reported here.  

However, for training, unless you use some tricks (like checkpointing and recomputing activiations) it is necessary to store all features in memory from the forward pass.  In this case the memory requirements will typically be at least as large as the parameter + feature memory.   I use the phrase "typically", because it's somewhat framework-specific though (particularly for the memory used in the backwards pass, which can heavily depend on the implementation details).

**Comment by hellobb237** [comment]
It is crystal clear! thank you
